[package]
name = "array-section"
authors = ["Johanna Sörngård (jsorngard@gmail.com)"]
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = "2021"
keyowrds = ["array", "const", "subarray"]
description = "An array where only a (contiguous) subarray may be viwed or operated on"
repository = "https://github.com/JSorngard/array-section"

[dependencies]

[features]
std = ["alloc"]
alloc = []

# docs.rs-specific configuration
[package.metadata.docs.rs]
# document all features
all-features = true
